custom html title for `Handout` class
danijar/handout pull request #14
Opened 2019-08-06 01:02 UTC by epogrebnyak

Added argument for custom html document title in `Handout` class  and proposed unit test layout.

2019-08-06 01:18 UTC, danijar commented
Thanks! To answer your question from #13, pytest is good. This doesn't change your test besides that you can use the `tmp_path` fixture.

Small nit: let's keep using single quote for consistency.

2019-08-06 23:20 UTC, danijar requested changes
Looks good. Please switch double to single quotes for consistency and use the `tmp_path` pytest fixture, i.e.:

```
import handout

 def test_handout_on_title_arg_inserts_title(tmp_path):
    output = handout.Handout(tmp_path, title='This string')._generate(source='')   
    assert '<title>This string</title>' in output 
```

2019-08-07 20:29 UTC, danijar requested changes

2019-08-07 20:29 UTC, danijar commented on handout/handout.py
> +  def __init__(self, directory, title="Handout"):
single quotes please

2019-08-07 21:04 UTC, epogrebnyak commented
Sorry adopting single quote was slow. Hope I'd be able to contribute to new PRs faster.

2019-08-08 03:33 UTC, merged

2019-08-08 03:33 UTC, danijar commented
No worries, thanks for the PR and your patience! :)